name: exobci
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pip
  - pip:
      - mne>=1.6.0
      - mne-bids>=0.13.0
      - pylsl>=1.16.2
      - brainflow>=5.12.0
      - pyyaml>=6.0.1
      - pygame>=2.5.2
      - pyxdf>=1.16.4
