frequencies_hz: [10, 12, 15, 20]
labels: ["A", "B", "C", "D"]
window_sec: 1.0
step_sec: 0.25
bandwidth_hz: 1.0
lsl:
  eeg_stream_type: "EEG"
  marker_stream_name: "markers"
eeg:
  expected_sampling_rate: 256
  n_channels: 4
  channel_names: ["Fz", "Cz", "Pz", "Oz"]
